spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
    url: jdbc:mysql:///openapi-admin
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 39.105.88.86
    port: 5672
